version: '3.8'

services:
  technocolabs-delivery-ai:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHON_VERSION=3.9
      - PORT=5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
